[project]
name = "12-mox-erc20-cu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mamushi>=0.0.3",
    "moccasin>=0.4.0",
    "snekmate>=0.1.1",
    "vyper>=0.4.1",
]

[tool.moccasin.project]
src = "contracts"
